[build]
  command = """
  curl -sL https://quarto.org/download/latest/quarto-linux-amd64.tar.gz -o quarto.tar.gz &&
  tar -xzf quarto.tar.gz &&
  ./quarto-*/bin/quarto render
  """
  publish = "_site"